version: '3.7'
services:
  jenkins:
    image: jenki-enomor
    build:
      context: .
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    restart: always
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - net
  

  remote_host:
   container_name: remote_host
   image: remote_host
   build:
    context: remote_user_dir
   restart: always
   networks:
      - net
networks:
  net:


 
   

    
















 
